site_name: Semantic Relatedness Shared Task
site_url: https://example.com/
theme:
  logo: assets/logo.png
  name: material
  font:
    text: Open Sans
    code: Roboto Mono
  palette:
     primary: pink
     accent: teal

nav:
    - Home: index.md
    # - Participation: participation.md
    - Resources: Resources.md
    - Organizers: organizer.md
    - Terms: Terms.md
    # - Results: results.md
    # - Awards: prizes.md
